# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/nuevo_conteo/nuevo_conteo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NuevoConteoWindow(object):
    def setupUi(self, NuevoConteoWindow):
        NuevoConteoWindow.setObjectName("NuevoConteoWindow")
        NuevoConteoWindow.resize(429, 487)

        self.centralwidget = QtWidgets.QWidget(NuevoConteoWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 60, 171, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 160, 51, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 161, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 260, 121, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 160, 151, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 310, 161, 17))
        self.label_7.setObjectName("label_7")

        self.localidad = QtWidgets.QLineEdit(self.centralwidget)
        self.localidad.setGeometry(QtCore.QRect(10, 30, 411, 25))
        self.localidad.setObjectName("localidad")

        self.nombre_muestra = QtWidgets.QLineEdit(self.centralwidget)
        self.nombre_muestra.setGeometry(QtCore.QRect(10, 80, 411, 25))
        self.nombre_muestra.setObjectName("nombre_muestra")

        self.nombre_unidad = QtWidgets.QLineEdit(self.centralwidget)
        self.nombre_unidad.setGeometry(QtCore.QRect(10, 130, 411, 25))
        self.nombre_unidad.setObjectName("nombre_unidad")

        self.numero = QtWidgets.QSpinBox(self.centralwidget)
        self.numero.setGeometry(QtCore.QRect(50, 180, 48, 26))
        self.numero.setObjectName("numero")

        self.fecha = QtWidgets.QDateEdit(self.centralwidget)
        self.fecha.setGeometry(QtCore.QRect(150, 180, 110, 26))
        self.fecha.setCalendarPopup(True)
        self.fecha.setObjectName("fecha")

        self.cantidad_lecturas = QtWidgets.QSpinBox(self.centralwidget)
        self.cantidad_lecturas.setGeometry(QtCore.QRect(310, 180, 71, 26))
        self.cantidad_lecturas.setMinimum(1)
        self.cantidad_lecturas.setMaximum(1000)
        self.cantidad_lecturas.setObjectName("cantidad_lecturas")

        self.latitud = QtWidgets.QLineEdit(self.centralwidget)
        self.latitud.setGeometry(QtCore.QRect(10, 230, 201, 25))
        self.latitud.setObjectName("latitud")

        self.longitud = QtWidgets.QLineEdit(self.centralwidget)
        self.longitud.setGeometry(QtCore.QRect(220, 230, 201, 25))
        self.longitud.setObjectName("longitud")

        self.profundidad = QtWidgets.QSpinBox(self.centralwidget)
        self.profundidad.setGeometry(QtCore.QRect(10, 280, 201, 26))
        self.profundidad.setMaximum(100000)
        self.profundidad.setObjectName("profundidad")

        self.operador = QtWidgets.QLineEdit(self.centralwidget)
        self.operador.setGeometry(QtCore.QRect(220, 280, 201, 25))
        self.operador.setObjectName("operador")

        self.observaciones = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.observaciones.setGeometry(QtCore.QRect(10, 330, 411, 70))
        self.observaciones.setObjectName("observaciones")

        self.cargar_mapa_boton = QtWidgets.QPushButton(self.centralwidget)
        self.cargar_mapa_boton.setGeometry(QtCore.QRect(10, 410, 221, 25))
        self.cargar_mapa_boton.setObjectName("cargar_mapa_boton")

        self.nuevo_mapa_boton = QtWidgets.QPushButton(self.centralwidget)
        self.nuevo_mapa_boton.setGeometry(QtCore.QRect(10, 440, 221, 25))
        self.nuevo_mapa_boton.setObjectName("nuevo_mapa_boton")

        self.cancelar_aceptar_boton = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.cancelar_aceptar_boton.setGeometry(QtCore.QRect(250, 440, 170, 25))
        self.cancelar_aceptar_boton.setStandardButtons(
            QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.cancelar_aceptar_boton.setObjectName("cancelar_aceptar_boton")

        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 81, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 210, 81, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(220, 210, 81, 17))
        self.label_10.setObjectName("label_10")

        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(250, 410, 161, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(220, 260, 81, 17))
        self.label_12.setObjectName("label_12")

        NuevoConteoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NuevoConteoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 429, 22))
        self.menubar.setObjectName("menubar")

        NuevoConteoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(NuevoConteoWindow)
        self.statusbar.setObjectName("statusbar")
        NuevoConteoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(NuevoConteoWindow)
        QtCore.QMetaObject.connectSlotsByName(NuevoConteoWindow)

    def retranslateUi(self, NuevoConteoWindow):
        _translate = QtCore.QCoreApplication.translate
        NuevoConteoWindow.setWindowTitle(_translate("NuevoConteoWindow", "Nuevo conteo"))
        self.label.setText(_translate("NuevoConteoWindow", "Nombre de la muestra *"))
        self.label_2.setText(_translate("NuevoConteoWindow", "Fecha"))
        self.label_3.setText(_translate("NuevoConteoWindow", "Localidad *"))
        self.label_4.setText(_translate("NuevoConteoWindow", "Número de muestra"))
        self.label_5.setText(_translate("NuevoConteoWindow", "Profundidad (m)"))
        self.label_6.setText(_translate("NuevoConteoWindow", "Cantidad de lecturas *"))
        self.label_7.setText(_translate("NuevoConteoWindow", "Observaciones"))
        self.nuevo_mapa_boton.setText(_translate("NuevaMuestraWindow", "Crear nuevo mapa de teclas"))
        self.cargar_mapa_boton.setText(_translate("NuevaMuestraWindow", "Cargar mapa de teclas"))
        self.label_8.setText(_translate("NuevoConteoWindow", "Unidad"))
        self.label_9.setText(_translate("NuevoConteoWindow", "Latitud"))
        self.label_10.setText(_translate("NuevoConteoWindow", "Longitud"))
        self.label_11.setText(_translate("NuevoConteoWindow",
                                         "<html><head/><body><p><span style=\" font-size:9pt;\">* Obligatorio</span></p></body></html>"))
        self.label_12.setText(_translate("NuevoConteoWindow", "Operador/a"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NuevoConteoWindow = QtWidgets.QMainWindow()
    ui = Ui_NuevoConteoWindow()
    ui.setupUi(NuevoConteoWindow)
    NuevoConteoWindow.show()
    sys.exit(app.exec_())
