# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/menu_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QFont
from PyQt5.QtWidgets import QWidget, QPushButton, QStatusBar, QMenuBar, QLabel

# from pyqt5_auto_translate import \
#     TranslatedQLabel as QLabel, \
#     TranslatedQPushButton as QPushButton, translater, \
#     ExampleTranslateMenuBar, load_ui_with_translation


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(322, 520)

        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.nuevaMuestraButton = QPushButton("Nueva muestra", self.centralwidget)
        self.nuevaMuestraButton.setGeometry(QtCore.QRect(20, 20, 281, 91))
        self.nuevaMuestraButton.setObjectName("pushButton")

        self.cargarMuestraButton = QPushButton("Cargar muestra", self.centralwidget)
        self.cargarMuestraButton.setGeometry(QtCore.QRect(20, 130, 281, 91))
        self.cargarMuestraButton.setObjectName("pushButton_2")

        self.generarGraficosBoton = QPushButton("Generar gráficos", self.centralwidget)
        self.generarGraficosBoton.setGeometry(QtCore.QRect(20, 240, 281, 91))
        self.generarGraficosBoton.setObjectName("graficosBoton")

        self.instruccionesBoton = QPushButton("Instrucciones", self.centralwidget)
        self.instruccionesBoton.setGeometry(QtCore.QRect(20, 350, 281, 91))
        self.instruccionesBoton.setObjectName("instruccionesBoton")

        self.label = QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 430, 281, 91))
        self.label.setObjectName("label")

        # creating label
        self.imagen = QLabel(self.centralwidget)
        # loading image
        self.pixmap = QPixmap('logo_conicet.jpg').scaledToWidth(322)
        # Optional, resize label to image size
        self.imagen.move(0, 500)
        # adding image to label
        self.imagen.setPixmap(self.pixmap)

        MainWindow.setCentralWidget(self.centralwidget)

        self.menubar = QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 222))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.nuevaMuestraButton.setStyleSheet(''' font-size: 24px; ''')
        self.cargarMuestraButton.setStyleSheet(''' font-size: 24px; ''')
        self.generarGraficosBoton.setStyleSheet(''' font-size: 24px; ''')
        self.instruccionesBoton.setStyleSheet(''' font-size: 24px; ''')
        self.label.setStyleSheet(''' font-size: 14px; ''')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "@Cont.Ar"))
        self.nuevaMuestraButton.setText(_translate("MainWindow", "Nueva muestra"))
        self.cargarMuestraButton.setText(_translate("MainWindow", "Cargar muestra"))
        self.generarGraficosBoton.setText(_translate("MainWindow", "Generar gráficos"))
        self.label.setText(_translate("Dialog", "Desarrollo y programación:\n"
                                                "Dra. Maisa Tunik\n"
                                                "Lic. Lucas Somacal"))

    def resizeEvent(self, event):
        self.imagen.resize(self.centralwidget.width(), self.imagen.height())
        self.imagen.setPixmap(self.imagen.pixmap().scaled(self.imagen.size(), QtCore.Qt.IgnoreAspectRatio))
        self.imagen.move(0, self.centralwidget.height() - self.imagen.height())
        QWidget.resizeEvent(self.centralwidget, event)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
